import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CytoscapeComponent from 'react-cytoscapejs';
//import { JsonEditor } from 'rc-json-editor';
import Input from "../components/InputComponent/Input";

export default function Home({data}) {
  console.log(data);
  
  return (
    
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    

      <main className={styles.main}>

      <h1>ProofVisualization</h1>
      <Input/>
      
      
      <CytoscapeComponent 
          elements={[
            { data: { id: 'one', label: 'Node 1' }, position: { x: 30, y: 100 } },
            { data: { id: 'two', label: 'Node 2' }, position: { x: 100, y: 100 } },
            { data: { source: 'one', target: 'two', label: 'Edge from Node1 to Node2' } }]}                
          style={{ width: '600px', height: '600px' }}/>  
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

/* export const getStaticProps = async () => {
  const res = await fetch(
    `http://localhost:3000/api/form`
  );
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}; */