import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, {useState, createContext} from "react";
import Input from "../components/InputComponent/Input";
import GraphCalculation from "../Components/GraphCalculation/GraphCalculation"


export const DataContext = createContext();

export default function Home({}) {
  
  const [values, setValues] = useState({
    textInput: "",
    radioButtonColor: "",
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <DataContext.Provider value={{ values, setValues }}>
          <Input />
          <GraphCalculation />
        </DataContext.Provider>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image
              src="/vercel.svg"
              alt="Vercel Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
